features:
  enabled_features: ["product", "user", "interaction_sequence", "geo", "country", "price", "category"]
  feature_configs:
    product:
      enabled: true
      type: pretrained_embedding
      dim: 200
      description: Product embeddings
    
    user:
      enabled: true
      type: pretrained_embedding
      dim: 200
      description: User embeddings
    
    interaction_sequence:
      enabled: false
      type: sequence
      input_dim: 200
      dim: 128
      max_seq_length: 50
      num_products: 1000
      transformer_config:
        nhead: 4
        num_layers: 2
        dim_feedforward: 256
        dropout: 0.1
      description: Sequential product interactions
    
    geo:
      enabled: true
      type: text
      dim: 64
      model_name: "distilbert-base-uncased"
      description: Geographic location text
    
    country:
      enabled: true
      type: text
      dim: 64
      model_name: "distilbert-base-uncased"
      description: Country text
    
    price:
      enabled: true
      type: numeric
      dim: 1
      description: Product price
    
    category:
      enabled: true
      type: categorical
      dim: 1
      num_categories: 10
      description: Product category

model:
  architecture: "dcn_v2"
  dcn_config:
    cross_layers: 3
    num_heads: 4
    hidden_layers: [512, 256, 128]
    task_hidden_layers: [64, 32]
    dropout_rate: 0.1
    activation: "gelu"
    use_batch_norm: false
    use_layer_norm: true
    cross_dropout: 0.1
    stochastic_depth_rate: 0.2
    feature_dropout: 0.05
    layer_wise_lr_decay: 0.9

training:
  optimizer:
    name: "adamw"
    learning_rate: 0.001
    weight_decay: 0.01
    beta1: 0.9
    beta2: 0.999
    layer_wise_lr: true
  
  scheduler:
    enabled: true
    type: "cosine"
    warmup_steps: 1000
    min_lr: 1e-6
    num_cycles: 3
  
  training_config:
    batch_size: 32
    num_epochs: 50
    train_split: 0.8
    validation_split: 0.1
    test_split: 0.1
    early_stopping: 5
    gradient_clipping: 1.0
    mixed_precision: true
    gradient_centralization: true
    manifold_mixup: true
    mixup_alpha: 0.2

tasks:
  click:
    enabled: true
    weight: 0.4
    loss: "bce"
    metrics: ["auc", "accuracy", "precision", "recall"]
    description: Click prediction
  
  purchase:
    enabled: true
    weight: 0.4
    loss: "bce"
    metrics: ["auc", "accuracy", "precision", "recall"]
    description: Purchase prediction
    
  add_to_cart:
    enabled: true
    weight: 0.2
    loss: "bce"
    metrics: ["auc", "accuracy", "precision", "recall"]
    description: Add to cart prediction

logging:
  wandb:
    enabled: false
    project: "reranker"
    entity: "your-team"
  
  tensorboard:
    enabled: true
    log_dir: "logs/tensorboard"
  
  checkpointing:
    save_best: true
    save_frequency: 5
    max_checkpoints: 3

data:
  input:
    max_sequence_length: 50
    padding_value: 0
    truncation: "right"
    
  augmentation:
    enabled: false
    sequence_masking_prob: 0.15
    feature_dropout: 0.1
    
  sampling:
    negative_sampling_ratio: 3
    max_samples_per_user: 100

paths:
  model_save_dir: "models/"
  best_model_path: "models/best_model.pth"
  log_dir: "logs/"

device: "cpu" 