features:
  enabled_features:
    - geo
    - country
    - price_0
    - category_0
    - page_type
    - age
    - gender
    - region
    - product_body_part
    - product_gender
    - product_age_desc
    - product_taxonomy_id
    - anchor_body_part
    - anchor_gender
    - anchor_age_desc
    - anchor_taxonomy_id
    - event_dow
    - anchor_embeds

  feature_configs:
    geo:
      enabled: true
      type: categorical
      dim: 16
      num_categories: 100
    country:
      enabled: true
      type: categorical
      dim: 16
      num_categories: 100
    price_0:
      enabled: true
      type: numeric
      dim: 16
    category_0:
      enabled: true
      type: categorical
      dim: 16
      num_categories: 100
    page_type:
      enabled: true
      type: categorical
      dim: 1
      num_categories: 8
    age:
      enabled: true
      type: categorical
      dim: 1
      num_categories: 6
    gender:
      enabled: true
      type: categorical
      dim: 1
      num_categories: 3
    region:
      enabled: true
      type: categorical
      dim: 1
      num_categories: 10
    product_body_part:
      enabled: true
      type: categorical
      dim: 1
      num_categories: 20
    product_gender:
      enabled: true
      type: categorical
      dim: 1
      num_categories: 3
    product_age_desc:
      enabled: true
      type: categorical
      dim: 1
      num_categories: 6
    product_taxonomy_id:
      enabled: true
      type: categorical
      dim: 1
      num_categories: 100
    anchor_body_part:
      enabled: true
      type: categorical
      dim: 1
      num_categories: 20
    anchor_gender:
      enabled: true
      type: categorical
      dim: 1
      num_categories: 3
    anchor_age_desc:
      enabled: true
      type: categorical
      dim: 1
      num_categories: 6
    anchor_taxonomy_id:
      enabled: true
      type: categorical
      dim: 1
      num_categories: 100
    event_dow:
      enabled: true
      type: categorical
      dim: 1
      num_categories: 7
    anchor_embeds:
      enabled: true
      type: pretrained_embedding
      dim: 64

model:
  architecture: "dcn_v2_moe"
  dcn_config:
    cross_layers: 2
    num_heads: 1
    hidden_layers: [256, 128, 64]
    task_hidden_layers: [32, 16]
    dropout_rate: 0.1
    activation: "relu"
    use_batch_norm: true
    use_layer_norm: false
    cross_dropout: 0.1
    stochastic_depth_rate: 0.1
    feature_dropout: 0.05
    layer_wise_lr_decay: 0.9
  moe_config:
    enabled: true
    num_experts: 5
    expert_hidden_size: 256
    gating_hidden_size: 128
    load_balancing_loss_weight: 0.1
    expert_dropout: 0.1
    use_region_specific_experts: true
    knowledge_distillation_weight: 0.5
    training_stages:
      global_expert_epochs: 5
      regional_expert_epochs: 3

training:
  optimizer:
    name: "adamw"
    learning_rate: 0.001
    weight_decay: 0.01
    beta1: 0.9
    beta2: 0.999
    layer_wise_lr: true
  
  scheduler:
    enabled: true
    type: "cosine"
    warmup_steps: 100
    min_lr: 1.0e-6
    num_cycles: 3
    warmup_ratio: 0.1
    cycle_decay: 0.1
  
  training_config:
    batch_size: 32
    num_epochs: 10
    train_split: 0.7
    validation_split: 0.15
    test_split: 0.15
    early_stopping:
      patience: 3
      min_delta: 0.001
    gradient_clipping: 1.0
    mixed_precision: true
    gradient_centralization: true
    manifold_mixup: true
    mixup_alpha: 0.2
    eval_frequency: 100
    save_best_k: 3
    accumulate_grad_batches: 1

tasks:
  click:
    enabled: true
    weight: 0.4
    loss: "bce"
    metrics: ["auc", "ndcg", "map", "precision_at_k", "recall_at_k"]
  purchase:
    enabled: true
    weight: 0.4
    loss: "bce"
    metrics: ["auc", "ndcg", "map", "precision_at_k", "recall_at_k"]
  add_to_cart:
    enabled: true
    weight: 0.2
    loss: "bce"
    metrics: ["auc", "ndcg", "map", "precision_at_k", "recall_at_k"]

logging:
  wandb:
    enabled: false
  tensorboard:
    enabled: true
    log_dir: "logs/tensorboard"
  checkpointing:
    save_best: true
    save_frequency: 5
    max_checkpoints: 3

paths:
  model_save_dir: "models/"
  best_model_path: "models/best_model.pth"
  log_dir: "logs/"

device: "cpu"

data:
  input:
    max_sequence_length: 50
    padding_value: 0
    truncation: "right"
    
  augmentation:
    enabled: false
    sequence_masking_prob: 0.15
    feature_dropout: 0.1
    
  sampling:
    negative_sampling_ratio: 3
    max_samples_per_user: 100

hyperparameter_tuning:
  enabled: false 